Add model mobilenet-v1(#5)
Adlik/model_optimizer_tf pull request #10
Opened 2020-07-10 01:32 UTC by ChengcanWang-com

Signed-off-by: Chengcan Wang <wang.chengcan@zte.com.cn>

2020-07-15 08:56 UTC, ChengcanWang-com commented
Close #5

2020-07-16 08:01 UTC, EFanZh requested changes
Can those “.gitkeep” file be remove and have those directories being created on-demand?

2020-07-16 08:01 UTC, EFanZh commented on examples/mobilenet_v1_imagenet_train.py
> +        "dataset": "imagenet",  # or imagenet
Invalid comment.

2020-07-16 08:01 UTC, EFanZh commented on src/model_optimizer/pruner/models/mobilenet_v1.py
> +def _mobilenet_v1(num_classes=1000,
Why not use `keras.applications.MobileNet` directly?

2020-07-17 06:54 UTC, ChengcanWang-com commented on examples/mobilenet_v1_imagenet_train.py
> +        "dataset": "imagenet",  # or imagenet
ok. Delete already created directories, these directories will be created automatically by the program.

2020-07-17 06:57 UTC, ChengcanWang-com commented on src/model_optimizer/pruner/models/mobilenet_v1.py
> +def _mobilenet_v1(num_classes=1000,
There are several reasons:
1. Keras.applications.MobileNet does not define initialze regularity and other parameters.
2. The BN layer of the keras model does not pass in the is_training parameter. Dropout is also the best infer and training to distinguish whether there is dropout.
3. The keras.applications.MobileNet pre-training model is actually transferred from the tensorflow model, why is it not trained by keras itself. It's a bit strange.

2020-07-17 07:10 UTC, EFanZh requested changes

2020-07-17 07:10 UTC, EFanZh commented on src/model_optimizer/__init__.py
> +        os.makedirs(file_path)
Use `os.makedirs(file_path, exists_ok=True)`.

2020-07-17 07:46 UTC, EFanZh commented
@ChengcanWang-com The CI tests have failed.

2020-07-20 01:45 UTC, EFanZh commented
bors r+

2020-07-20 01:53 UTC, closed without merging