Support benchmark about model optimization
Adlik/model_optimizer_tf pull request #12
Opened 2020-07-29 03:28 UTC by priscilla-pan

Closes #6

2020-08-01 06:35 UTC, shiyingjin requested changes

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/client_script/resnet50_client_script.sh
> +#!/usr/bin/env bash
Use "#!/usr/bin/env bash -e"

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/client_script/resnet50_client_script.sh
> +python3 /home/john/Adlik/benchmark/tests/client/$CLIENT_INFERENCE_SCRIPT --model-name=resnet50  --batch-size=100 /home/john/Adlik/benchmark/tests/data/$IMAGE_FILENAME && \
Don't use path like "/home/jonh/.....". We can't assume the user's work path.

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/client_script/resnet50_pruned_client_script.sh
> +#!/usr/bin/env bash
Use "#!/usr/bin/env bash -e"

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/serving_script/resnet50_pruned_serving_script.sh
> +#!/usr/bin/env bash
Use "#!/usr/bin/env bash -e"

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/serving_script/resnet50_serving_script.sh
> +#!/usr/bin/env bash
Use "#!/usr/bin/env bash -e"

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test.sh
> +#!/usr/bin/env bash
Use "#!/usr/bin/env bash -e"

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test_pruned.sh
> +#!/usr/bin/env bash
Use "#!/usr/bin/env bash -e"

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test_pruned.sh
> +cd ../../../../
Where am I?

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test.sh
> +cd ../../../../
Where am I?

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/client_script/resnet50_client_script.sh
> +python3 /home/john/Adlik/benchmark/tests/client/$CLIENT_INFERENCE_SCRIPT --model-name=resnet50  --batch-size=100 /home/john/Adlik/benchmark/tests/data/$IMAGE_FILENAME && \
Use double quotes to enclose parameters

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tests/client_script/resnet50_pruned_client_script.sh
> +python3 /home/john/Adlik/benchmark/tests/client/$CLIENT_INFERENCE_SCRIPT --model-name=resnet50_pruned  --batch-size=100 /home/john/Adlik/benchmark/tests/data/$IMAGE_FILENAME && \
Use double quotes to enclose parameters

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test.sh
> +cp -r $optimizer_benchmark_path/tests $adlik_benchmark_path
Use double quotes to enclose parameters

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test.sh
> +python3 benchmark/src/automatic_test.py -d benchmark/tests/docker_test/tensorflow_gpu.Dockerfile -s tensorflow_gpu -b . -a . -m resnet50  -c benchmark/tests/client_script/resnet50_client_script.sh -s
The parameters of "automatic_test.py" are hard to understand

2020-08-01 06:35 UTC, shiyingjin commented on benchmark/tools/resnet50/automatic_test_pruned.sh
> +cp -r $optimizer_benchmark_path/tests $adlik_benchmark_path
Use double quotes to enclose parameters

2020-08-01 07:25 UTC, shiyingjin approved these changes

2020-08-01 07:49 UTC, ChengcanWang-zte approved these changes

2020-08-03 02:18 UTC, amadeus-zte commented on benchmark/tools/resnet50/automatic_test.sh
> +cd ../../../../
There is a hypothesis that current path of this runtime env is ‘xxxx’. 
It is not acceptable for users. Please give some general solutions.

2020-08-13 06:05 UTC, amadeus-zte commented
bors r+

2020-08-13 06:14 UTC, closed without merging