Support model pruning and quantization
Adlik/model_optimizer_tf pull request #4
Opened 2020-05-22 01:18 UTC by ChengcanWang-com

Close #3

2020-06-11 06:58 UTC, shiyingjin requested changes

2020-06-11 06:58 UTC, shiyingjin commented on ResNet-50-Traing-Pruning.md
> +# ResNet-50 training and pruning
Put this file into a separate directory

2020-06-15 01:59 UTC, EFanZh requested changes

2020-06-15 01:59 UTC, EFanZh commented on README.md
>  [![Bors enabled](https://bors.tech/images/badge_small.svg)](https://app.bors.tech/repositories/23640)
Put these lines after the title.

2020-06-15 01:59 UTC, EFanZh commented on docker/Dockerfile.cpu
> +        add-apt-repository ppa:deadsnakes/ppa && \
No need to use external Python repository. The Python from official Ubuntu 18.04 packages is 3.6.

2020-06-15 01:59 UTC, EFanZh commented on docker/Dockerfile.cpu
> +    pip install  --no-cache-dir mpi4py==3.0.3 && \
Dependencies specified in `setup.py` will be automatically installed when the target package is being installed. So you don’t need to install them manually.

2020-06-15 05:54 UTC, shiyingjin approved these changes

2020-06-15 09:11 UTC, EFanZh commented
bors r+

2020-06-15 09:11 UTC, EFanZh approved these changes

2020-06-15 09:19 UTC, closed without merging